version: "3"

services:
  frontend:
    image: "privoas/frontend-production"
    mem_limit: 128m
    hostname: frontend
  server:
    image: "privoas/server-production"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "privoas/worker-production"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "privoas/nginx-production"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"